feat(vibevoice): add ASR support (#8222)
* feat(vibevoice): add ASR support

Signed-off-by: Ettore Di Giacinto <mudler@localai.io>

* Add tests

Signed-off-by: Ettore Di Giacinto <mudler@localai.io>

* fixups

Signed-off-by: Ettore Di Giacinto <mudler@localai.io>

* chore(tests): download voice files

Signed-off-by: Ettore Di Giacinto <mudler@localai.io>

* Small fixups

Signed-off-by: Ettore Di Giacinto <mudler@localai.io>

* Small fixups

Signed-off-by: Ettore Di Giacinto <mudler@localai.io>

* Try to run on bigger runner

Signed-off-by: Ettore Di Giacinto <mudler@localai.io>

* Fixups

Signed-off-by: Ettore Di Giacinto <mudler@localai.io>

* Fixups

Signed-off-by: Ettore Di Giacinto <mudler@localai.io>

* Fixups

Signed-off-by: Ettore Di Giacinto <mudler@localai.io>

* debug

Signed-off-by: Ettore Di Giacinto <mudler@localai.io>

* CI can't hold vibevoice

Signed-off-by: Ettore Di Giacinto <mudler@localai.io>

---------

Signed-off-by: Ettore Di Giacinto <mudler@localai.io>

diff --git a/backend/python/vibevoice/Makefile b/backend/python/vibevoice/Makefile
--- a/backend/python/vibevoice/Makefile
+++ b/backend/python/vibevoice/Makefile
@@ -2,6 +2,43 @@
 vibevoice:
 	bash install.sh
 
+.PHONY: download-voices
+download-voices:
+	@echo "Downloading voice preset files..."
+	@mkdir -p voices/streaming_model
+	@if command -v wget >/dev/null 2>&1; then \
+		wget -q -O voices/streaming_model/en-Frank_man.pt \
+			https://raw.githubusercontent.com/microsoft/VibeVoice/main/demo/voices/streaming_model/en-Frank_man.pt && \
+		wget -q -O voices/streaming_model/en-Grace_woman.pt \
+			https://raw.githubusercontent.com/microsoft/VibeVoice/main/demo/voices/streaming_model/en-Grace_woman.pt && \
+		wget -q -O voices/streaming_model/en-Mike_man.pt \
+			https://raw.githubusercontent.com/microsoft/VibeVoice/main/demo/voices/streaming_model/en-Mike_man.pt && \
+		wget -q -O voices/streaming_model/en-Emma_woman.pt \
+			https://raw.githubusercontent.com/microsoft/VibeVoice/main/demo/voices/streaming_model/en-Emma_woman.pt && \
+		wget -q -O voices/streaming_model/en-Carter_man.pt \
+			https://raw.githubusercontent.com/microsoft/VibeVoice/main/demo/voices/streaming_model/en-Carter_man.pt && \
+		wget -q -O voices/streaming_model/en-Davis_man.pt \
+			https://raw.githubusercontent.com/microsoft/VibeVoice/main/demo/voices/streaming_model/en-Davis_man.pt && \
+		echo "Voice files downloaded successfully"; \
+	elif command -v curl >/dev/null 2>&1; then \
+		curl -sL -o voices/streaming_model/en-Frank_man.pt \
+			https://raw.githubusercontent.com/microsoft/VibeVoice/main/demo/voices/streaming_model/en-Frank_man.pt && \
+		curl -sL -o voices/streaming_model/en-Grace_woman.pt \
+			https://raw.githubusercontent.com/microsoft/VibeVoice/main/demo/voices/streaming_model/en-Grace_woman.pt && \
+		curl -sL -o voices/streaming_model/en-Mike_man.pt \
+			https://raw.githubusercontent.com/microsoft/VibeVoice/main/demo/voices/streaming_model/en-Mike_man.pt && \
+		curl -sL -o voices/streaming_model/en-Emma_woman.pt \
+			https://raw.githubusercontent.com/microsoft/VibeVoice/main/demo/voices/streaming_model/en-Emma_woman.pt && \
+		curl -sL -o voices/streaming_model/en-Carter_man.pt \
+			https://raw.githubusercontent.com/microsoft/VibeVoice/main/demo/voices/streaming_model/en-Carter_man.pt && \
+		curl -sL -o voices/streaming_model/en-Davis_man.pt \
+			https://raw.githubusercontent.com/microsoft/VibeVoice/main/demo/voices/streaming_model/en-Davis_man.pt && \
+		echo "Voice files downloaded successfully"; \
+	else \
+		echo "Error: Neither wget nor curl found. Cannot download voice files."; \
+		exit 1; \
+	fi
+
 .PHONY: run
 run: vibevoice
 	@echo "Running vibevoice..."
@@ -9,7 +46,7 @@ run: vibevoice
 	@echo "vibevoice run."
 
 .PHONY: test
-test: vibevoice
+test: vibevoice download-voices
 	@echo "Testing vibevoice..."
 	bash test.sh
 	@echo "vibevoice tested."
